base:
    seed: &seed 42
model:
    type: Qwen2
    path: /nfs/FM/chenshuailin/checkpoints/Qwen/Qwen3-4B-Instruct-2507
    torch_dtype: auto
calib:
    name: pileval
    path: data/pileval
    preproc: pileval_awq
    n_samples: 128
    seq_len: 512
    download: False
    bs: -1
    seed: *seed
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
        calib_algo: learnable
        pack_version: gemm_pack
    special:
        trans: True
        # trans_version: v2
        weight_clip: False
        clip_version: v1
        # clip_sym: True
save:
    # save_trans: true
    # save_fake: True
    save_autoawq: True
    # save_vllm: True
    save_path: checkpoints/Qwen3-4B-Instruct-2507/awq/w4a16_asym_g128
dispatch:
    num_gpus: 1
    # safe_margin: 0.5