base:
    seed: &seed 42
model:
    type: Llama
    path: /nfs/FM/chenshuailin/checkpoints/LLM-Research/Meta-Llama-3___1-8B-Instruct
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
calib:
    name: pileval
    download: False
    path: data/pileval
    n_samples: 256
    bs: 1
    seq_len: 4096
    preproc: txt_general_preproc
    seed: *seed
quant:
    method: SmoothQuant
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        alpha: 0.5
save:
    # save_vllm_nvfp4: True
    save_vllm: True
    save_trans: True
    # save_fake: True
    save_path: checkpoints/llama3.1-8B-it/smoothqunat/pileval_n256_s4k_a0.5_sym_w4a8
dispatch:
    num_gpus: 1
