base:
    seed: &seed 42
model:
    type: Qwen2
    path: checkpoints/Qwen2.5-3B-Instruct/awq/w4a16g64_asym_cilp/transformed_model
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
calib:
    name: wikitext2
    preproc: wikitext2_gptq
    path: data/wikitext2
    download: False
    n_samples: 128
    bs: 1
    seq_len: 2048
    seed: *seed
quant:
    method: RTN
    weight:
        quant_type: nvfp4
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 16
        share_global_scale: True
        calib_algo: minmax
    act:
        quant_type: nvfp4
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 16
        share_global_scale: True
        calib_algo: static_minmax
        static: True
    special:
        # actorder: True
        # static_groups: True
        # percdamp: 0.05
        # blocksize: 128
        # chunk_num: 1
        true_sequential: True
        # online_rotate: True
        # fp32_had: False
        # online_rotate_exclude: ["o_proj"]
        # eager_transform_dtype: True
        # force_scale_dtype: True
    quant_out: True
save:
    # save_fake: True
    # save_vllm: True
    # save_autoawq: True
    save_vllm_nvfp4: True
    save_path: checkpoints/Qwen2.5-3B-Instruct/RTN/awq_clip_nvf4_w4a4_sgs
dispatch:
    num_gpus: 1