base:
    seed: &seed 42
model:
    type: Qwen2
    path: checkpoints/Qwen2.5-3B-Instruct/quarot/group_rotate_g16/transformed_model
    tokenizer_mode: fast
    torch_dtype: torch.bfloat16
quant:
    method: RTN
    weight:
        quant_type: nvfp4
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 16
        share_global_scale: True
save:
    save_fake: True
    # save_vllm: True
    # save_autoawq: True
    save_vllm_nvfp4: True
    save_path: checkpoints/Qwen2.5-3B-Instruct/RTN/quarot_g16_rtn_nvfp4_w4a16_sgs
dispatch:
    num_gpus: 1