base:
    seed: &seed 42
model:
    type: Qwen2
    path: /nfs/FM/chenshuailin/checkpoints/Qwen/Qwen3-0.6B
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
        pack_version: gemm_pack
save:
    save_fake: True
    # save_vllm: True
    save_autoawq: True
    save_path: checkpoints/Qwen3-0.6B/rtn/asym_w4a16g128
dispatch:
    num_gpus: 1