base:
    seed: &seed 0
model:
    type: Qwen2
    path: checkpoints/Qwen2.5-3B-Instruct/quarot/nvfp4_w4a16_sgs_olrotate/transformed_model_cleaned
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: data/wikitext2
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: True
        granularity: per_channel
        calib_algo: mse
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        chunk_num: 4
        true_sequential: True
        online_rotate: True
        fp32_had: True
    quant_out: True
save:
    save_trans: True
    save_fake: True
    save_vllm: True
    save_path: checkpoints/Qwen2.5-3B-Instruct/gptq/sym_w4a8_dynamic_ol-rotate
dispatch:
    num_gpus: 1